/* eslint-disable react-hooks/set-state-in-effect -- preserve existing async screen-loading behavior. */
import { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { AppScreen, Card, StatusBadge } from '@/src/components/ui';
import { AppHeader, EmptyState, ErrorState, LoadingIndicator } from '@/src/components/shared';
import { normalizeError } from '@/src/services/api/errors';
import { colors, spacing, typography } from '@/src/theme/tokens';
import { questionApi, type Question } from '@/src/features/questions/api/questionApi';
import { examApi, type ExamVersion, type GeneratedExam } from '../api/examApi';
import { RoleGate } from '@/src/app/navigation/RoleGate';

export function ExamDetailScreen() { return <RoleGate roles={['SUBJECT_ADMIN']}><ExamDetailContent /></RoleGate>; }
function ExamDetailContent() {
  const { id, version } = useLocalSearchParams<{ id: string; version?: string }>(); const router = useRouter(); const [exam, setExam] = useState<GeneratedExam | null>(null); const [selected, setSelected] = useState<ExamVersion | null>(null); const [previews, setPreviews] = useState<Record<string, Question | null>>({}); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { if (!id) return; setLoading(true); setError(null); try { const result = await examApi.getExam(id); setExam(result); const chosen = result.versions.find(item => String(item.version) === String(version)) || result.versions[0] || null; setSelected(chosen); if (chosen) { const entries = await Promise.all(chosen.questions.map(async ref => { try { return [ref.questionId, await questionApi.get(ref.questionId)] as const; } catch { return [ref.questionId, null] as const; } })); setPreviews(Object.fromEntries(entries)); } } catch (cause) { setError(normalizeError(cause).message); } finally { setLoading(false); } }, [id, version]);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <AppScreen><AppHeader title="Chi tiết bộ đề" /><LoadingIndicator label="Đang tải bộ đề" /></AppScreen>;
  if (error) return <AppScreen><AppHeader title="Chi tiết bộ đề" /><ErrorState title={error} onRetry={() => void load()} /></AppScreen>;
  if (!exam) return <AppScreen><AppHeader title="Chi tiết bộ đề" /><EmptyState title="Không tìm thấy bộ đề" /></AppScreen>;
  return <AppScreen scroll><AppHeader title={exam.name} subtitle="Chế độ xem trước" /><Card><Text style={styles.label}>Môn học</Text><Text style={styles.value}>{exam.subjectId}</Text><Text style={styles.label}>Ma trận / mẫu đề</Text><Text style={styles.value}>{exam.matrixId} / {exam.templateId || 'Chưa có'}</Text><Text style={styles.label}>Tạo lúc</Text><Text style={styles.value}>{new Date(exam.createdAt).toLocaleString('vi-VN')}</Text></Card><Text style={styles.section}>Phiên bản</Text>{exam.versions.map(item => <Pressable key={item.id} accessibilityRole="button" onPress={() => router.push({ pathname: '/exams/[id]/version/[version]', params: { id: exam.id, version: String(item.version) } })}><Card><Text style={styles.value}>Phiên bản {item.version}</Text><Text style={styles.meta}>{item.questions.length} câu tham chiếu · {new Date(item.createdAt).toLocaleString('vi-VN')}</Text><StatusBadge label={selected?.id === item.id ? 'Đang chọn' : 'Xem trước'} tone={selected?.id === item.id ? 'success' : 'neutral'} /></Card></Pressable>)}{selected && <><Text style={styles.section}>Xem trước câu hỏi · Phiên bản {selected.version}</Text>{selected.questions.map(ref => { const question = previews[ref.questionId]; return <Card key={ref.id}><Text style={styles.position}>Câu {ref.position}</Text>{question ? <><Text style={styles.value}>{question.content}</Text><Text style={styles.meta}>{question.difficulty} · {question.source} · {question.status}</Text><StatusBadge label="Xem trước câu hỏi" tone="neutral" /></> : <EmptyState title="Không thể tải câu hỏi" description="Không thể tải câu hỏi qua API Gateway." />}</Card>; })}</>}</AppScreen>;
}
const styles = StyleSheet.create({ section: { color: colors.text, fontSize: typography.heading, fontWeight: '700', marginBottom: spacing.sm, marginTop: spacing.md }, label: { color: colors.textSecondary, fontSize: typography.caption, marginTop: spacing.sm }, value: { color: colors.text, fontSize: typography.body, fontWeight: '600' }, meta: { color: colors.textSecondary, fontSize: typography.caption, marginTop: spacing.sm }, position: { color: colors.accent, fontWeight: '700', marginBottom: spacing.sm } });
