import { StyleSheet, Text, View } from 'react-native';
import { Card, StatusBadge } from '@/src/components/ui';
import { useElapsedTime } from '@/src/hooks/useElapsedTime';
import { asyncStatusLabels, formatElapsedTime } from '@/src/utils/asyncProgress';
import { colors, radius, spacing, typography } from '@/src/theme/tokens';

type Step = { id?: string; label: string; status?: string };
type Props = { title: string; status: string; progress?: number | null; startedAt?: string | null; completedAt?: string | null; currentStep?: string | null; steps?: Step[]; message?: string; canLeave?: boolean };
export function AsyncProgressCard({ title, status, progress, startedAt, completedAt, currentStep, steps, message, canLeave = false }: Props) {
  const active = ['PENDING', 'PROCESSING', 'RETRYING'].includes(status); const elapsed = useElapsedTime(startedAt, completedAt, active); const determinate = typeof progress === 'number' && progress >= 0 && progress <= 100; const label = asyncStatusLabels[status] || status;
  return <Card><View style={styles.header}><View style={styles.titleWrap}><Text style={styles.title}>{title}</Text>{currentStep ? <Text style={styles.step}>{currentStep}</Text> : null}</View><StatusBadge label={label} tone={status === 'COMPLETED' ? 'success' : status === 'FAILED' ? 'danger' : 'warning'} /></View>{message ? <Text style={styles.message}>{message}</Text> : null}{active ? <View accessibilityRole="progressbar" accessibilityLabel={determinate ? `Tiến trình ${Math.round(progress as number)}%` : 'Tiến trình đang xử lý'} accessibilityValue={determinate ? { min: 0, max: 100, now: progress as number } : undefined} style={styles.track}><View style={[styles.fill, determinate ? { width: `${progress}%` } : styles.indeterminate]} /></View> : null}{steps?.length ? <View style={styles.steps}>{steps.map(step => <Text key={step.id || step.label} style={[styles.stepRow, step.status === 'COMPLETED' && styles.completed]}>{step.status === 'COMPLETED' ? '✓' : step.status === 'PROCESSING' ? '●' : '○'} {step.label}</Text>)}</View> : null}<View style={styles.footer}><Text style={styles.meta}>{status === 'COMPLETED' ? 'Hoàn tất sau' : 'Đã xử lý'} <Text style={styles.strong}>{formatElapsedTime(elapsed)}</Text></Text>{canLeave && active ? <Text style={styles.leave}>Có thể rời màn hình</Text> : null}</View></Card>;
}
const styles = StyleSheet.create({ header: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }, titleWrap: { flex: 1, gap: spacing.xs }, title: { color: colors.text, fontSize: typography.body, fontWeight: '700' }, step: { color: colors.accent, fontSize: typography.caption, fontWeight: '700' }, message: { color: colors.textSecondary, fontSize: typography.caption, marginTop: spacing.sm }, track: { backgroundColor: colors.muted, borderRadius: radius.pill, height: 8, marginTop: spacing.md, overflow: 'hidden' }, fill: { backgroundColor: colors.accent, borderRadius: radius.pill, height: '100%' }, indeterminate: { width: '35%', opacity: 0.85 }, steps: { gap: spacing.xs, marginTop: spacing.md }, stepRow: { color: colors.textSecondary, fontSize: typography.caption }, completed: { color: colors.success }, footer: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, justifyContent: 'space-between', marginTop: spacing.md }, meta: { color: colors.textSecondary, fontSize: typography.caption }, strong: { color: colors.text, fontWeight: '700' }, leave: { color: colors.accent, fontSize: typography.caption, fontWeight: '700' } });
