/* eslint-disable react-hooks/set-state-in-effect -- preserve existing async screen-loading behavior. */
import { useCallback, useEffect, useState } from 'react';
import { StyleSheet, Text } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { AppScreen, Button, Card, ConfirmModal, StatusBadge } from '@/src/components/ui';
import { AppHeader, EmptyState, ErrorState, LoadingIndicator } from '@/src/components/shared';
import { normalizeError } from '@/src/services/api/errors';
import { colors, spacing, typography } from '@/src/theme/tokens';
import { RoleGate } from '@/src/app/navigation/RoleGate';
import { adminApi, type AdminUser } from '../api/adminApi';

type Action = 'approve' | 'reject' | 'lock' | 'unlock';
const actionTitles: Record<Action, string> = { approve: 'Phê duyệt tài khoản', reject: 'Từ chối tài khoản', lock: 'Khóa tài khoản', unlock: 'Mở khóa tài khoản' };
const roleLabel = (role: AdminUser['role']) => role === 'SYSTEM_ADMIN' ? 'Quản trị viên hệ thống' : role === 'SUBJECT_ADMIN' ? 'Quản trị viên chuyên môn' : 'Giảng viên';

export function AdminUserDetailScreen() { return <RoleGate roles={['SYSTEM_ADMIN']}><AdminUserDetailContent /></RoleGate>; }
function AdminUserDetailContent() { const { id } = useLocalSearchParams<{ id: string }>(); const [user, setUser] = useState<AdminUser | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [action, setAction] = useState<Action | null>(null); const [busy, setBusy] = useState(false); const load = useCallback(async () => { if (!id) return; setLoading(true); setError(null); try { setUser(await adminApi.getUser(id)); } catch (cause) { setError(normalizeError(cause).message); } finally { setLoading(false); } }, [id]); useEffect(() => { void load(); }, [load]); async function confirmAction() { if (!user || !action) return; setBusy(true); setError(null); try { setUser(await adminApi[action](user.id)); setAction(null); } catch (cause) { setError(normalizeError(cause).message); } finally { setBusy(false); } } if (loading) return <AppScreen><AppHeader title="Chi tiết người dùng" /><LoadingIndicator label="Đang tải người dùng" /></AppScreen>; if (error && !user) return <AppScreen><AppHeader title="Chi tiết người dùng" /><ErrorState title={error} onRetry={() => void load()} /></AppScreen>; if (!user) return <AppScreen><AppHeader title="Chi tiết người dùng" /><EmptyState title="Không tìm thấy người dùng" /></AppScreen>; const canApprove = user.status === 'PENDING_APPROVAL'; const canLock = user.status === 'ACTIVE'; const canUnlock = user.status === 'LOCKED'; return <AppScreen scroll><AppHeader title="Chi tiết người dùng" subtitle={user.lecturerCode} /><Card><Text style={styles.name}>{user.fullName || user.lecturerCode}</Text><Text style={styles.value}>{user.email}</Text><StatusBadge label={user.status} tone={user.status === 'ACTIVE' ? 'success' : user.status === 'REJECTED' || user.status === 'LOCKED' ? 'danger' : 'warning'} /><Text style={styles.label}>Khoa</Text><Text style={styles.value}>{user.facultyId || 'Chưa phân công'}</Text><Text style={styles.label}>Vai trò</Text><Text style={styles.value}>{roleLabel(user.role)}</Text><Text style={styles.label}>Điện thoại</Text><Text style={styles.value}>{user.phone || 'Chưa cập nhật'}</Text><Text style={styles.label}>Ngày tạo</Text><Text style={styles.value}>{new Date(user.createdAt).toLocaleString('vi-VN')}</Text></Card>{error && <ErrorState title={error} />}{canApprove && <><Button title="Phê duyệt" onPress={() => setAction('approve')} /><Button title="Từ chối" variant="destructive" onPress={() => setAction('reject')} /></>}{canLock && <Button title="Khóa tài khoản" variant="destructive" onPress={() => setAction('lock')} />}{canUnlock && <Button title="Mở khóa tài khoản" onPress={() => setAction('unlock')} />}<ConfirmModal visible={action !== null} title={action ? actionTitles[action] : ''} description={action === 'reject' ? 'API hiện tại không nhận lý do từ chối.' : 'Bạn có chắc muốn thực hiện thao tác này không?'} onCancel={() => { if (!busy) setAction(null); }} onConfirm={() => void confirmAction()} /></AppScreen>; }
const styles = StyleSheet.create({ name: { color: colors.text, fontSize: typography.heading, fontWeight: '700' }, label: { color: colors.textSecondary, fontSize: typography.caption, marginTop: spacing.md }, value: { color: colors.text, fontSize: typography.body, marginTop: spacing.xs } });
