/* eslint-disable react-hooks/set-state-in-effect -- preserve existing async screen-loading behavior. */
import { useCallback, useEffect, useState } from 'react';
import { FlatList, Pressable, RefreshControl, StyleSheet, Text } from 'react-native';
import { useRouter } from 'expo-router';
import { AppScreen, Card, StatusBadge } from '@/src/components/ui';
import { AppHeader, EmptyState, ErrorState, LoadingIndicator } from '@/src/components/shared';
import { RoleGate } from '@/src/app/navigation/RoleGate';
import { normalizeError } from '@/src/services/api/errors';
import { colors, spacing, typography } from '@/src/theme/tokens';
import { adminApi, type AdminUser } from '../api/adminApi';

export function ApprovalsScreen() { return <RoleGate roles={['SYSTEM_ADMIN']}><ApprovalsContent /></RoleGate>; }
function ApprovalsContent() { const router = useRouter(); const [items, setItems] = useState<AdminUser[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null); const load = useCallback(async (refresh = false) => { if (refresh) setRefreshing(true); else setLoading(true); setError(null); try { const result = await adminApi.listUsers(0, 20, { status: 'PENDING_APPROVAL' }); setItems(result.content); } catch (cause) { setError(normalizeError(cause).message); } finally { setLoading(false); setRefreshing(false); } }, []); useEffect(() => { void load(); }, [load]); if (loading) return <AppScreen><AppHeader title="Tài khoản chờ phê duyệt" /><LoadingIndicator label="Đang tải đăng ký chờ duyệt" /></AppScreen>; return <AppScreen><AppHeader title="Tài khoản chờ phê duyệt" subtitle={`${items.length} tài khoản đang chờ xử lý`} />{error && <ErrorState title={error} onRetry={() => void load()} />}{!error && <FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={items.length ? styles.list : styles.empty} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.accent} />} renderItem={({ item }) => <Pressable accessibilityRole="button" onPress={() => router.push({ pathname: '/admin/registration/[id]', params: { id: item.id } })}><Card><Text style={styles.title}>{item.fullName || item.lecturerCode}</Text><Text style={styles.meta}>{item.lecturerCode} · {item.email}</Text><Text style={styles.meta}>Khoa: {item.facultyId || 'Chưa phân công'}</Text><Text style={styles.meta}>{new Date(item.createdAt).toLocaleString('vi-VN')}</Text><StatusBadge label="PENDING_APPROVAL" tone="warning" /></Card></Pressable>} ListEmptyComponent={<EmptyState title="Không có tài khoản chờ phê duyệt" description="Danh sách sẽ cập nhật khi có đăng ký mới." />} />}</AppScreen>; }
const styles = StyleSheet.create({ list: { gap: spacing.md, paddingBottom: spacing.xl }, empty: { flexGrow: 1 }, title: { color: colors.text, fontSize: typography.body, fontWeight: '700' }, meta: { color: colors.textSecondary, fontSize: typography.caption, marginTop: spacing.sm } });
