/* eslint-disable react-hooks/set-state-in-effect -- preserve existing notification subscription behavior. */
import { useCallback, useEffect, useState } from 'react';
import { AppState, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { AppScreen, Button, Card, StatusBadge } from '@/src/components/ui';
import { AppHeader, EmptyState, ErrorState, LoadingIndicator } from '@/src/components/shared';
import { normalizeError } from '@/src/services/api/errors';
import { connectGatewaySocket } from '@/src/services/websocket/client';
import { colors, spacing, typography } from '@/src/theme/tokens';
import { notificationApi, type NotificationItem } from '../api/notificationApi';

function isNotification(value: unknown): value is NotificationItem { if (!value || typeof value !== 'object') return false; const item = value as Partial<NotificationItem>; return typeof item.id === 'string' && typeof item.title === 'string' && typeof item.type === 'string'; }

export function NotificationsScreen() {
  const router = useRouter(); const [items, setItems] = useState<NotificationItem[]>([]); const [unread, setUnread] = useState(0); const [tab, setTab] = useState<'all' | 'unread'>('all'); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [busy, setBusy] = useState(false); const [socketStatus, setSocketStatus] = useState<'connecting' | 'connected' | 'disconnected'>('disconnected'); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (refresh = false) => { if (refresh) setRefreshing(true); else setLoading(true); setError(null); try { const [list, count] = await Promise.all([notificationApi.list(), notificationApi.unreadCount()]); setItems(list); setUnread(count.count); } catch (cause) { setError(normalizeError(cause).message); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); const unsubscribe = connectGatewaySocket({ onStatus: status => { setSocketStatus(status); if (status === 'connected') void load(true); }, onMessage: message => { if (!isNotification(message)) return; setItems(current => current.some(item => item.id === message.id) ? current : [message, ...current]); if (!message.read) setUnread(current => current + 1); } }); return unsubscribe; }, [load]);
  useEffect(() => { const subscription = AppState.addEventListener('change', state => { if (state === 'active') void load(true); }); return () => subscription.remove(); }, [load]);
  async function markRead(item: NotificationItem) { if (item.read) { navigateReference(item); return; } setBusy(true); try { const updated = await notificationApi.markRead(item.id); setItems(current => current.map(existing => existing.id === updated.id ? updated : existing)); setUnread(current => Math.max(0, current - 1)); navigateReference(updated); } catch (cause) { setError(normalizeError(cause).message); } finally { setBusy(false); } }
  async function markAll() { setBusy(true); try { await notificationApi.markAllRead(); await load(true); } catch (cause) { setError(normalizeError(cause).message); } finally { setBusy(false); } }
  function navigateReference(item: NotificationItem) { const id = item.referenceId; if (!id) return; const type = (item.referenceType || '').toUpperCase(); if (type.includes('AI') || item.type === 'AI_GENERATION_COMPLETED' || item.type === 'AI_GENERATION_FAILED') router.push({ pathname: '/ai/job/[id]', params: { id } }); else if (type.includes('QUESTION') || item.type.startsWith('QUESTION_')) router.push({ pathname: '/question/[id]', params: { id } }); }
  if (loading) return <AppScreen><AppHeader title="Thông báo" /><LoadingIndicator label="Đang tải thông báo" /></AppScreen>;
  const visible = tab === 'unread' ? items.filter(item => !item.read) : items;
  return <AppScreen><AppHeader title="Thông báo" subtitle={`${unread} chưa đọc`} /><View style={styles.toolbar}><StatusBadge label={socketStatus === 'connected' ? 'Đang kết nối realtime' : socketStatus === 'connecting' ? 'Đang kết nối' : 'Đồng bộ REST'} tone={socketStatus === 'connected' ? 'success' : 'neutral'} /><Button title="Đọc tất cả" variant="secondary" loading={busy} disabled={busy || unread === 0} onPress={() => void markAll()} /></View><View style={styles.tabs}><Pressable style={[styles.tab, tab === 'all' && styles.activeTab]} onPress={() => setTab('all')}><Text style={[styles.tabLabel, tab === 'all' && styles.activeTabLabel]}>Tất cả</Text></Pressable><Pressable style={[styles.tab, tab === 'unread' && styles.activeTab]} onPress={() => setTab('unread')}><Text style={[styles.tabLabel, tab === 'unread' && styles.activeTabLabel]}>Chưa đọc</Text></Pressable></View>{error && <ErrorState title={error} onRetry={() => void load()} />}{!error && <FlatList data={visible} keyExtractor={item => item.id} contentContainerStyle={visible.length ? styles.list : styles.emptyList} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.accent} />} renderItem={({ item }) => <Pressable accessibilityRole="button" onPress={() => void markRead(item)}><Card style={!item.read ? styles.unreadCard : undefined}><View style={styles.row}><Ionicons name={item.read ? 'notifications-outline' : 'notifications'} size={20} color={item.read ? colors.textSecondary : colors.accent} /><Text style={styles.title}>{item.title}</Text>{!item.read && <View accessibilityLabel="Chưa đọc" style={styles.dot} />}</View><Text style={styles.content}>{item.content}</Text><Text style={styles.timestamp}>{new Date(item.createdAt).toLocaleString('vi-VN')}</Text>{item.referenceId && <Text style={styles.reference}>Mở nội dung liên quan</Text>}</Card></Pressable>} ListEmptyComponent={<EmptyState title="Chưa có thông báo" description={tab === 'unread' ? 'Bạn đã đọc tất cả thông báo.' : 'Thông báo sẽ xuất hiện tại đây khi có cập nhật mới.'} />} />}</AppScreen>;
}

const styles = StyleSheet.create({ toolbar: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.md }, tabs: { backgroundColor: colors.muted, borderRadius: 8, flexDirection: 'row', marginBottom: spacing.md, padding: 3 }, tab: { alignItems: 'center', borderRadius: 6, flex: 1, paddingVertical: spacing.sm }, activeTab: { backgroundColor: colors.surface }, tabLabel: { color: colors.textSecondary, fontSize: typography.caption, fontWeight: '700' }, activeTabLabel: { color: colors.accent }, list: { gap: spacing.md, paddingBottom: spacing.xl }, emptyList: { flexGrow: 1 }, unreadCard: { borderColor: colors.accent, borderWidth: 1.5 }, row: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm }, title: { color: colors.text, flex: 1, fontSize: typography.body, fontWeight: '700' }, dot: { backgroundColor: colors.accent, borderRadius: 5, height: 10, marginLeft: spacing.sm, width: 10 }, content: { color: colors.textSecondary, fontSize: typography.body, marginTop: spacing.sm }, timestamp: { color: colors.textSecondary, fontSize: typography.caption, marginTop: spacing.md }, reference: { color: colors.accent, fontSize: typography.caption, marginTop: spacing.sm } });
