/* eslint-disable react-hooks/set-state-in-effect -- initial REST synchronization updates screen state. */
import { useCallback, useEffect, useState } from 'react';
import { FlatList, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { AppScreen, Button, Card, StatusBadge } from '@/src/components/ui';
import { AppHeader, EmptyState, ErrorState, LoadingIndicator } from '@/src/components/shared';
import { normalizeError } from '@/src/services/api/errors';
import { useThemeColors } from '@/src/theme/useThemeColors';
import { spacing, typography } from '@/src/theme/tokens';
import { Assignment, assignmentApi, DirectoryUser } from '../api/assignmentApi';
const statusLabels: Record<string, string> = { ASSIGNED: 'Đã giao', IN_PROGRESS: 'Đang thực hiện', SUBMITTED: 'Chờ phê duyệt', COMPLETED: 'Hoàn thành', OVERDUE: 'Quá hạn' };
export function AssignedWorkScreen() {
  const router = useRouter(); const colors = useThemeColors(); const [items, setItems] = useState<Assignment[]>([]); const [subjects, setSubjects] = useState<Map<string, string>>(new Map()); const [people, setPeople] = useState<Map<string, DirectoryUser>>(new Map()); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async (refresh = false) => { if (refresh) setRefreshing(true); try { const [assignments, catalog] = await Promise.all([assignmentApi.list(), assignmentApi.subjects()]); const ids = [...new Set(assignments.flatMap(item => [item.assignedBy, item.lecturerId]).filter(Boolean))]; const directory = ids.length ? await assignmentApi.directory(ids) : []; setItems(assignments); setSubjects(new Map(catalog.map(item => [item.id, `${item.code ? `${item.code} - ` : ''}${item.name}`]))); setPeople(new Map(directory.map(item => [item.userId, item]))); setError(''); } catch (cause) { setError(normalizeError(cause).message); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <AppScreen><AppHeader title="Công việc được giao" /><LoadingIndicator label="Đang tải công việc" /></AppScreen>;
  return <AppScreen><AppHeader title="Công việc được giao" subtitle="Tiến độ được tính từ dữ liệu câu hỏi thực tế" />{error ? <ErrorState title={error} onRetry={() => void load()} /> : <FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={items.length ? styles.list : styles.empty} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.accent} />} renderItem={({ item }) => { const assignedBy = people.get(item.assignedBy); return <Card><View style={styles.head}><Text style={[styles.subject, { color: colors.text }]}>{subjects.get(item.subjectId) || 'Không xác định'}</Text><StatusBadge label={statusLabels[item.status] || item.status} tone={item.status === 'COMPLETED' ? 'success' : item.status === 'OVERDUE' ? 'danger' : 'warning'} /></View><Text style={[styles.meta, { color: colors.textSecondary }]}>Giao bởi: {assignedBy?.fullName || 'Không xác định'}{assignedBy?.lecturerCode ? ` · ${assignedBy.lecturerCode}` : ''}</Text><Text style={[styles.requirement, { color: colors.text }]}>Yêu cầu: {item.requiredQuestionCount} câu · E/M/H {item.requiredEasy}/{item.requiredMedium}/{item.requiredHard}</Text><View style={styles.progress}><Text style={{ color: colors.textSecondary }}>Đã tạo: {item.progress?.total || 0}/{item.requiredQuestionCount}</Text><Text style={{ color: colors.textSecondary }}>Đã duyệt: {item.progress?.approved || 0}/{item.requiredQuestionCount}</Text></View><Text style={[styles.meta, { color: colors.textSecondary }]}>Hạn: {new Date(item.deadline).toLocaleDateString('vi-VN')}</Text><Button title="Tạo câu hỏi cho công việc" variant="secondary" onPress={() => router.push({ pathname: '/question/create', params: { assignmentId: item.id, subjectId: item.subjectId, chapterId: item.chapterId || '', topicId: item.topicId || '', knowledgeItemId: item.knowledgeItemId || '' } })} /></Card>; }} ListEmptyComponent={<EmptyState title="Chưa có công việc được giao" description="Công việc mới sẽ xuất hiện tại đây sau khi quản trị viên chuyên môn phân công." />} />}</AppScreen>;
}
const styles = StyleSheet.create({ list: { gap: spacing.md, paddingBottom: 110 }, empty: { flexGrow: 1 }, head: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between' }, subject: { flex: 1, fontSize: typography.body, fontWeight: '800' }, meta: { fontSize: typography.caption, marginTop: spacing.sm }, requirement: { fontSize: typography.label, fontWeight: '700', marginTop: spacing.md }, progress: { flexDirection: 'row', gap: spacing.lg, marginVertical: spacing.md } });
