import { useEffect, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { AuthLayout } from '@/src/features/auth/components/AuthLayout';
import { AuthError } from '@/src/features/auth/components/AuthError';
import { authApi } from '@/src/features/auth/api/authApi';
import { facultyApi, type PublicFaculty } from '@/src/features/auth/api/facultyApi';
import { authErrorMessage } from '@/src/features/auth/model/authMessages';
import { Button, Input, Select } from '@/src/components/ui';
import { colors, radius, spacing, typography } from '@/src/theme/tokens';

export function RegisterScreen() {
  const router=useRouter();const[lecturerCode,setLecturerCode]=useState('');const[fullName,setFullName]=useState('');const[email,setEmail]=useState('');const[facultyId,setFacultyId]=useState('');const[facultyName,setFacultyName]=useState('');const[password,setPassword]=useState('');const[confirmPassword,setConfirmPassword]=useState('');const[consent,setConsent]=useState(false);const[faculties,setFaculties]=useState<PublicFaculty[]>([]);const[facultyOpen,setFacultyOpen]=useState(false);const[facultyError,setFacultyError]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false);
  useEffect(()=>{facultyApi.list().then(result=>setFaculties(result.content||[])).catch(()=>setFacultyError('Không thể tải danh sách Khoa.'))},[])
  async function submit(){setError('');if(password!==confirmPassword){setError('Mật khẩu xác nhận không khớp.');return}setLoading(true);try{await authApi.register({lecturerCode:lecturerCode.trim(),password,fullName:fullName.trim(),email:email.trim(),facultyId});router.replace('/(auth)/pending-approval')}catch(reason){setError(authErrorMessage(reason,'Không thể đăng ký tài khoản.'))}finally{setLoading(false)}}
  const invalid=!lecturerCode.trim()||!fullName.trim()||!email.trim()||!facultyId||password.length<8||password!==confirmPassword||!consent||loading;
  return <AuthLayout title="Đăng ký tài khoản" description="Tài khoản mới cần được Quản trị viên hệ thống phê duyệt trước khi đăng nhập."><View style={styles.form}><AuthError message={error}/><Input label="Mã giảng viên" value={lecturerCode} onChangeText={setLecturerCode} autoCapitalize="characters" autoComplete="username"/><Input label="Họ và tên" value={fullName} onChangeText={setFullName} autoComplete="name"/><Input label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoComplete="email"/><Select label="Khoa đăng ký" value={facultyName} placeholder={facultyError||'Chọn Khoa'} onPress={()=>setFacultyOpen(true)}/><Input label="Mật khẩu" value={password} onChangeText={setPassword} secureTextEntry autoComplete="new-password"/><Text style={styles.hint}>Mật khẩu cần có tối thiểu 8 ký tự.</Text><Input label="Xác nhận mật khẩu" value={confirmPassword} onChangeText={setConfirmPassword} secureTextEntry autoComplete="new-password" error={confirmPassword&&password!==confirmPassword?'Mật khẩu xác nhận không khớp.':undefined}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:consent}} onPress={()=>setConsent(value=>!value)} style={styles.consent}><View style={[styles.checkbox,consent&&styles.checked]}>{consent&&<Text style={styles.check}>✓</Text>}</View><Text style={styles.consentText}>Tôi đồng ý với Điều khoản sử dụng và Chính sách bảo mật.</Text></Pressable><Button title="Đăng ký tài khoản" loading={loading} disabled={invalid} onPress={()=>void submit()}/></View><Modal visible={facultyOpen} transparent animationType="slide" onRequestClose={()=>setFacultyOpen(false)}><Pressable style={styles.backdrop} onPress={()=>setFacultyOpen(false)}><View style={styles.sheet}><Text style={styles.sheetTitle}>Chọn Khoa</Text>{faculties.map(faculty=><Pressable key={faculty.id||faculty.code} style={styles.choice} onPress={()=>{setFacultyId(faculty.code||faculty.id);setFacultyName(faculty.name);setFacultyOpen(false)}}><Text style={styles.choiceText}>{faculty.name}</Text></Pressable>)}</View></Pressable></Modal></AuthLayout>;
}
const styles=StyleSheet.create({form:{gap:spacing.lg},hint:{color:colors.textSecondary,fontSize:typography.caption},consent:{alignItems:'flex-start',flexDirection:'row',gap:spacing.sm},checkbox:{alignItems:'center',borderColor:colors.border,borderRadius:radius.sm,borderWidth:1,height:22,justifyContent:'center',width:22},checked:{backgroundColor:colors.accent,borderColor:colors.accent},check:{color:colors.white,fontWeight:'700'},consentText:{color:colors.textSecondary,flex:1,fontSize:typography.caption,lineHeight:19},backdrop:{backgroundColor:'rgba(0,0,0,.25)',flex:1,justifyContent:'flex-end'},sheet:{backgroundColor:colors.surface,borderTopLeftRadius:radius.lg,borderTopRightRadius:radius.lg,gap:spacing.sm,maxHeight:'70%',padding:spacing.xl},sheetTitle:{color:colors.text,fontSize:typography.heading,fontWeight:'700'},choice:{borderBottomColor:colors.border,borderBottomWidth:StyleSheet.hairlineWidth,paddingVertical:spacing.md},choiceText:{color:colors.text,fontSize:typography.body}});
