/* eslint-disable react-hooks/set-state-in-effect -- preserve existing polling behavior. */
import { useCallback, useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { AppScreen, Card, StatusBadge } from '@/src/components/ui';
import { AppHeader, AsyncProgressCard, EmptyState, ErrorState, LoadingIndicator } from '@/src/components/shared';
import { aiApi, type AiJob, type GeneratedQuestion } from '../api/aiApi';
import { normalizeError } from '@/src/services/api/errors';
import { colors, spacing, typography } from '@/src/theme/tokens';

export function AiJobScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [job, setJob] = useState<AiJob | null>(null); const [result, setResult] = useState<GeneratedQuestion[] | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const poll = useCallback(async () => { if (!id) return; try { const next = await aiApi.getJob(id); setJob(next); setError(null); if (next.status === 'COMPLETED') setResult(await aiApi.getResult<GeneratedQuestion[]>(id)); if (next.status === 'FAILED') setError(next.errorMessage || 'Tác vụ AI không thể hoàn tất.'); } catch (cause) { setError(normalizeError(cause).message); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void poll(); }, [poll]); useEffect(() => { if (!job || job.status === 'COMPLETED' || job.status === 'FAILED') return; const timer = setInterval(() => void poll(), 3000); return () => clearInterval(timer); }, [job, poll]);
  if (loading) return <AppScreen><AppHeader title="Chi tiết tác vụ AI" /><LoadingIndicator label="Đang tải tác vụ" /></AppScreen>;
  if (!job) return <AppScreen><AppHeader title="Chi tiết tác vụ AI" /><ErrorState title={error || 'Không tìm thấy tác vụ'} onRetry={() => void poll()} /></AppScreen>;
  return <AppScreen scroll><AppHeader title="Chi tiết tác vụ AI" subtitle="Trạng thái theo dữ liệu hệ thống" /><AsyncProgressCard title={job.type === 'QUESTION_GENERATION' ? 'Tạo câu hỏi bằng AI' : job.type === 'ANALYSIS' ? 'Phân tích tài liệu' : 'Trợ lý học liệu'} status={job.status} startedAt={job.startedAt || job.createdAt} completedAt={job.completedAt} canLeave message={job.status === 'PROCESSING' ? 'API hiện chưa cung cấp phần trăm tiến độ.' : undefined} />{error && <ErrorState title={error} onRetry={() => void poll()} />}{job.status === 'COMPLETED' && result ? <View><Text style={styles.generated}>Câu hỏi được tạo</Text><Text style={styles.disclaimer}>Đây là bản nháp, chưa phải câu hỏi đã phê duyệt.</Text>{result.map((item, index) => <Card key={`${item.question}-${index}`}><Text style={styles.question}>{item.question}</Text>{item.options?.map(option => <Text key={option.label} style={styles.option}>{option.label}. {option.content}{option.label === item.correctAnswer ? ' ✓' : ''}</Text>)}<Text style={styles.meta}>Đáp án đúng: {item.correctAnswer}</Text><Text style={styles.meta}>Độ khó: {item.difficulty || '—'} • Chủ đề: {item.topicId || '—'}</Text><Text style={styles.explanation}>{item.explanation}</Text><StatusBadge label="Bản nháp AI" /></Card>)}</View> : job.status === 'COMPLETED' ? <EmptyState title="Chưa có kết quả" description="Tác vụ đã hoàn tất nhưng chưa trả về dữ liệu có cấu trúc." /> : null}</AppScreen>;
}
const styles = StyleSheet.create({ generated: { color: colors.text, fontSize: typography.heading, fontWeight: '700', marginTop: spacing.xl }, disclaimer: { color: colors.warning, fontSize: typography.caption, marginBottom: spacing.md, marginTop: spacing.sm }, question: { color: colors.text, fontSize: typography.body, fontWeight: '700' }, option: { color: colors.text, fontSize: typography.body, marginTop: spacing.md }, explanation: { color: colors.textSecondary, fontSize: typography.body, marginVertical: spacing.md }, meta: { color: colors.textSecondary, fontSize: typography.caption, marginTop: spacing.sm } });
