/* eslint-disable react-hooks/set-state-in-effect -- preserve existing async screen-loading behavior. */
import { useCallback, useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { useRouter } from 'expo-router';
import { AppScreen, Button, Card, Input, StatusBadge } from '@/src/components/ui';
import { AppHeader, EmptyState, ErrorState, LoadingIndicator } from '@/src/components/shared';
import { aiApi, type AiJob, type DocumentItem } from '../api/aiApi';
import { normalizeError } from '@/src/services/api/errors';
import { colors, spacing, typography } from '@/src/theme/tokens';

const MAX_DOCUMENT_BYTES = 10 * 1024 * 1024;
const jobLabel: Record<string, string> = { PENDING: 'Đang chờ', PROCESSING: 'Đang xử lý', COMPLETED: 'Hoàn tất', FAILED: 'Thất bại' };

export function AiScreen() { const router = useRouter(); const [documents, setDocuments] = useState<DocumentItem[]>([]); const [jobs, setJobs] = useState<AiJob[]>([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [error, setError] = useState<string | null>(null); const [selectedDocument, setSelectedDocument] = useState<DocumentItem | null>(null); const [count, setCount] = useState('5'); const load = useCallback(async () => { setLoading(true); setError(null); try { const [documentPage, jobPage] = await Promise.all([aiApi.documents(), aiApi.jobs()]); setDocuments(documentPage.items); setJobs(jobPage.items); } catch (cause) { setError(normalizeError(cause).message); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  async function upload() { setError(null); const result = await DocumentPicker.getDocumentAsync({ type: 'text/plain', copyToCacheDirectory: true, multiple: false }); if (result.canceled) return; const file = result.assets[0]; if (file.mimeType !== 'text/plain') { setError('Chỉ hỗ trợ tệp văn bản UTF-8.'); return; } if (file.size && file.size > MAX_DOCUMENT_BYTES) { setError('Tệp vượt quá giới hạn 10 MB của hệ thống AI.'); return; } setUploading(true); try { await aiApi.uploadDocument({ uri: file.uri, name: file.name, mimeType: file.mimeType }); await load(); } catch (cause) { setError(normalizeError(cause).message); } finally { setUploading(false); } }
  async function createJob() { if (!selectedDocument) return; const parsed = Number(count); if (!Number.isInteger(parsed) || parsed < 1 || parsed > 100) { setError('Số câu phải từ 1 đến 100.'); return; } try { const job = await aiApi.createGeneration({ documentId: selectedDocument.id, count: parsed }); router.push({ pathname: '/ai/job/[id]', params: { id: job.jobId } }); } catch (cause) { setError(normalizeError(cause).message); } }
  if (loading) return <AppScreen><AppHeader title="Không gian AI" subtitle="Tài liệu và tạo câu hỏi" /><LoadingIndicator label="Đang tải không gian AI" /></AppScreen>;
  return <AppScreen scroll><AppHeader title="Không gian AI" subtitle="Tài liệu và tạo câu hỏi" />{error && <ErrorState title={error} onRetry={() => void load()} />}<View style={styles.actions}><Button title="Tải tài liệu" loading={uploading} disabled={uploading} onPress={() => void upload()} /><Button title="Trợ lý trò chuyện" variant="secondary" onPress={() => router.push({ pathname: '/ai/chat', params: { documentId: selectedDocument?.id || '' } })} /></View><Text style={styles.sectionTitle}>Tài liệu của tôi</Text>{documents.length ? documents.map(document => <Card key={document.id}><Text style={styles.name}>{document.originalName}</Text><Text style={styles.meta}>{document.contentType} • {(document.size / 1024).toFixed(1)} KB</Text><View style={styles.row}><Button title={selectedDocument?.id === document.id ? 'Đã chọn' : 'Chọn tài liệu'} variant={selectedDocument?.id === document.id ? 'primary' : 'secondary'} onPress={() => setSelectedDocument(document)} /><Button title="Tạo câu hỏi" onPress={() => { setSelectedDocument(document); Alert.alert('Tạo câu hỏi bằng AI', 'Đã chọn tài liệu. Hãy nhập số câu rồi xác nhận bên dưới.'); }} /></View></Card>) : <EmptyState title="Chưa có tài liệu" description="Tải tệp văn bản để bắt đầu." />}<Text style={styles.sectionTitle}>Tạo câu hỏi bằng AI</Text><Card><Text style={styles.meta}>{selectedDocument ? `Tài liệu: ${selectedDocument.originalName}` : 'Hãy chọn một tài liệu trước'}</Text><Input label="Số lượng câu hỏi" value={count} onChangeText={setCount} keyboardType="number-pad" /><Button title="Tạo câu hỏi bằng AI" disabled={!selectedDocument} onPress={() => void createJob()} /></Card><Text style={styles.sectionTitle}>Tác vụ AI</Text>{jobs.length ? jobs.map(job => <Card key={job.jobId}><View style={styles.row}><Text style={styles.name}>{job.type}</Text><StatusBadge label={jobLabel[job.status] || job.status} tone={job.status === 'COMPLETED' ? 'success' : job.status === 'FAILED' ? 'danger' : 'warning'} /></View><Text style={styles.meta}>{new Date(job.createdAt).toLocaleString('vi-VN')}</Text>{job.status === 'FAILED' && <Text style={styles.error}>{job.errorMessage || job.errorCode || 'Tác vụ AI thất bại.'}</Text>}<Button title="Xem tác vụ" variant="secondary" onPress={() => router.push({ pathname: '/ai/job/[id]', params: { id: job.jobId } })} /></Card>) : <EmptyState title="Chưa có tác vụ AI" description="Các tác vụ tạo câu hỏi hoặc xử lý tài liệu sẽ xuất hiện tại đây." />}</AppScreen>; }
const styles = StyleSheet.create({ actions: { gap: spacing.md }, sectionTitle: { color: colors.text, fontSize: typography.heading, fontWeight: '700', marginTop: spacing.xl, marginBottom: spacing.md }, name: { color: colors.text, fontSize: typography.body, fontWeight: '700' }, meta: { color: colors.textSecondary, fontSize: typography.caption, marginTop: spacing.sm }, row: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.md }, error: { color: colors.danger, fontSize: typography.caption, marginTop: spacing.sm } });
