import {useState} from 'react';
import {KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {useRouter} from 'expo-router';
import {AppScreen,Button,Card,Input} from '@/src/components/ui';
import {AppHeader,ErrorState} from '@/src/components/shared';
import {aiApi} from '../api/aiApi';
import {spacing,typography} from '@/src/theme/tokens';
import {useThemeColors} from '@/src/theme/useThemeColors';

type Message={role:'USER'|'ASSISTANT';content:string;actions?:{label:string;routeKey:string}[]};
const suggestions=['Cách tạo câu hỏi?','Cách gửi câu hỏi để duyệt?','Cách sử dụng AI?','Cách quản lý thông báo?'];
const routes:Record<string,string>={DASHBOARD:'/(tabs)',PROFILE:'/profile',NOTIFICATIONS:'/(tabs)/notifications',QUESTION_CREATE:'/question/create',MY_QUESTIONS:'/(tabs)/questions',AI_GENERATE:'/ai',AI_DOCUMENTS:'/ai',QUESTION_REVIEW:'/review',SUBJECTS:'/subjects',EXAM_MATRICES:'/exams',USERS:'/admin/users',FACULTIES:'/admin/faculties',SYSTEM_SETTINGS:'/admin/email-settings',CONTACT_REQUESTS:'/admin/contact'};

export function SystemHelpScreen(){const router=useRouter();const colors=useThemeColors();const[messages,setMessages]=useState<Message[]>([]);const[text,setText]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function send(value=text){const message=value.trim();if(!message||busy)return;setText('');setBusy(true);setError('');setMessages(current=>[...current,{role:'USER',content:message}]);try{const response=await aiApi.systemHelp(message);setMessages(current=>[...current,{role:'ASSISTANT',content:response.answer,actions:response.actions}])}catch(cause){setError(cause instanceof Error?cause.message:'Không thể nhận hướng dẫn lúc này.')}finally{setBusy(false)}return undefined}return <AppScreen><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS==='ios'?'padding':undefined}><AppHeader title="Trợ lý HAU QM" subtitle="Hướng dẫn sử dụng theo vai trò" showIdentity={false}/><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.messages}>{!messages.length&&<Card><Text style={[styles.welcome,{color:colors.text}]}>Bạn cần hướng dẫn chức năng nào?</Text><Text style={[styles.description,{color:colors.textSecondary}]}>Trợ lý chỉ hướng dẫn các quy trình HAU QM bạn được phép sử dụng.</Text><View style={styles.suggestions}>{suggestions.map(item=><Pressable key={item} style={[styles.suggestion,{borderColor:colors.border,backgroundColor:colors.muted}]} onPress={()=>void send(item)}><Text style={{color:colors.text}}>{item}</Text></Pressable>)}</View></Card>}{messages.map((message,index)=><Card key={`${message.role}-${index}`} style={[styles.message,message.role==='USER'&&{alignSelf:'flex-end',backgroundColor:colors.accentSoft}]}><Text style={[styles.role,{color:colors.textSecondary}]}>{message.role==='USER'?'Bạn':'Trợ lý HAU QM'}</Text><Text style={[styles.body,{color:colors.text}]}>{message.content}</Text>{message.actions?.map(action=>routes[action.routeKey]&&<Button key={action.routeKey} title={action.label} variant="secondary" onPress={()=>router.push(routes[action.routeKey] as never)}/>)}</Card>)}{busy&&<Text style={{color:colors.textSecondary}}>Trợ lý đang chuẩn bị hướng dẫn…</Text>}{error&&<ErrorState title={error}/>}</ScrollView><View style={styles.composer}><Input label="Câu hỏi" value={text} onChangeText={setText} multiline maxLength={1000} placeholder="Ví dụ: Làm sao gửi câu hỏi để duyệt?"/><Button title="Gửi" loading={busy} disabled={busy||!text.trim()} onPress={()=>void send()}/></View></KeyboardAvoidingView></AppScreen>}
const styles=StyleSheet.create({flex:{flex:1},messages:{gap:spacing.md,paddingBottom:spacing.lg},welcome:{fontSize:typography.body,fontWeight:'800'},description:{fontSize:typography.label,lineHeight:20,marginTop:spacing.sm},suggestions:{gap:spacing.sm,marginTop:spacing.lg},suggestion:{borderRadius:8,borderWidth:StyleSheet.hairlineWidth,padding:spacing.md},message:{gap:spacing.sm,maxWidth:'92%'},role:{fontSize:typography.caption,fontWeight:'700'},body:{fontSize:typography.body,lineHeight:24},composer:{gap:spacing.sm,paddingTop:spacing.sm}});
