/* eslint-disable react-hooks/set-state-in-effect -- preserve existing dependent catalog-loading behavior. */
import { useEffect, useMemo, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { AppScreen, Button, Card, Input, Select } from '@/src/components/ui';
import { AppHeader, ErrorState, LoadingIndicator } from '@/src/components/shared';
import { useAuth } from '@/src/app/providers/AppProviders';
import { normalizeError } from '@/src/services/api/errors';
import { colors, radius, spacing, typography } from '@/src/theme/tokens';
import { questionApi, type CatalogItem, type Difficulty, type QuestionInput, type QuestionOption, type QuestionType } from '../api/questionApi';

const typeChoices: QuestionType[] = ['SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'TRUE_FALSE'];
const difficultyChoices: Difficulty[] = ['EASY', 'MEDIUM', 'HARD'];
type Form = Omit<QuestionInput, 'options'> & { options: QuestionOption[] };
const blankOption = (label: string, sortOrder: number): QuestionOption => ({ label, content: '', imageUrl: null, storageKey: null, correct: false, sortOrder });
function newForm(facultyId: string): Form { return { facultyId, subjectId: '', chapterId: '', topicId: null, content: '', imageUrl: null, storageKey: null, type: 'SINGLE_CHOICE', difficulty: 'MEDIUM', options: ['A', 'B', 'C', 'D'].map((label, index) => blankOption(label, index)) }; }

export function QuestionEditorScreen() {
  const { id } = useLocalSearchParams<{ id?: string }>(); const router = useRouter(); const { session } = useAuth();
  const [form, setForm] = useState<Form>(() => newForm(session?.facultyId || '')); const [subjects, setSubjects] = useState<CatalogItem[]>([]); const [chapters, setChapters] = useState<CatalogItem[]>([]); const [topics, setTopics] = useState<CatalogItem[]>([]); const [choice, setChoice] = useState<{ title: string; items: CatalogItem[] | string[]; onPick: (value: string) => void } | null>(null); const [loading, setLoading] = useState(Boolean(id)); const [saving, setSaving] = useState(false); const [uploadingImage, setUploadingImage] = useState(false); const [error, setError] = useState<string | null>(null); const [validation, setValidation] = useState<string | null>(null);
  useEffect(() => { void questionApi.subjects(session?.facultyId).then(setSubjects).catch(() => undefined); }, [session?.facultyId]); useEffect(() => { if (form.subjectId) void questionApi.chapters(form.subjectId).then(setChapters).catch(() => setChapters([])); else setChapters([]); }, [form.subjectId]); useEffect(() => { if (form.chapterId) void questionApi.topics(form.chapterId).then(setTopics).catch(() => setTopics([])); else setTopics([]); }, [form.chapterId]); useEffect(() => { if (!id) return; questionApi.get(id).then(question => setForm({ facultyId: question.facultyId, subjectId: question.subjectId, chapterId: question.chapterId, topicId: question.topicId, content: question.content, imageUrl: question.imageUrl, storageKey: question.storageKey, type: question.type, difficulty: question.difficulty, options: question.options })).catch(cause => setError(normalizeError(cause).message)).finally(() => setLoading(false)); }, [id]);
  const subjectName = useMemo(() => subjects.find(item => item.id === form.subjectId)?.name, [form.subjectId, subjects]); const chapterName = useMemo(() => chapters.find(item => item.id === form.chapterId)?.name, [form.chapterId, chapters]); const topicName = useMemo(() => topics.find(item => item.id === form.topicId)?.name, [form.topicId, topics]);
  function update<K extends keyof Form>(key: K, value: Form[K]) { setForm(current => ({ ...current, [key]: value })); setValidation(null); } function updateOption(index: number, patch: Partial<QuestionOption>) { setForm(current => ({ ...current, options: current.options.map((option, optionIndex) => optionIndex === index ? { ...option, ...patch } : option) })); setValidation(null); } function selectCatalog(title: string, items: CatalogItem[], key: 'subjectId' | 'chapterId' | 'topicId') { setChoice({ title, items, onPick: value => { update(key, value); if (key === 'subjectId') update('chapterId', ''); if (key !== 'topicId') update('topicId', null); setChoice(null); } }); }
  async function pickImage(kind: 'question' | 'option', optionIndex?: number) { const result = await DocumentPicker.getDocumentAsync({ type: ['image/jpeg', 'image/png', 'image/webp', 'image/gif'], copyToCacheDirectory: true, multiple: false }); if (result.canceled || !result.assets[0]) return; const file = result.assets[0]; if (file.size && file.size > 5 * 1024 * 1024) { setError('Ảnh phải nhỏ hơn hoặc bằng 5MB.'); return; } setUploadingImage(true); setError(null); try { const stored = await questionApi.uploadImage({ uri: file.uri, name: file.name || 'question-image.jpg', mimeType: file.mimeType || 'image/jpeg' }, kind); const url = stored.secureUrl || stored.url; if (kind === 'question') setForm(current => ({ ...current, imageUrl: url, storageKey: stored.publicId })); else if (optionIndex !== undefined) updateOption(optionIndex, { imageUrl: url, storageKey: stored.publicId }); } catch (cause) { setError(normalizeError(cause).message); } finally { setUploadingImage(false); } }
  function validate() { if (!form.facultyId || !form.subjectId || !form.chapterId || !form.content.trim()) return 'Vui lòng nhập đầy đủ môn học, chương và nội dung câu hỏi.'; if (form.options.length === 0 || form.options.some(option => !option.content.trim())) return 'Mỗi phương án phải có nội dung.'; if (!form.options.some(option => option.correct)) return 'Hãy chọn đáp án đúng.'; return null; } async function save() { const issue = validate(); setValidation(issue); if (issue) return; setSaving(true); setError(null); try { const saved = id ? await questionApi.update(id, form) : await questionApi.create(form); router.replace({ pathname: '/question/[id]', params: { id: saved.id } }); } catch (cause) { setError(normalizeError(cause).message); } finally { setSaving(false); } }
  if (loading) return <AppScreen><AppHeader title="Chỉnh sửa câu hỏi" /><LoadingIndicator label="Đang tải câu hỏi" /></AppScreen>;
  return <AppScreen scroll><AppHeader title={id ? 'Chỉnh sửa câu hỏi' : 'Tạo câu hỏi'} subtitle="Ngân hàng câu hỏi" />{error && <ErrorState title={error} />}{validation && <Text style={styles.validation}>{validation}</Text>}<Card><Text style={styles.sectionTitle}>Phân loại</Text><Select label="Loại câu hỏi" value={form.type} onPress={() => setChoice({ title: 'Loại câu hỏi', items: typeChoices, onPick: value => { update('type', value as QuestionType); setChoice(null); } })} /><Select label="Độ khó" value={form.difficulty} onPress={() => setChoice({ title: 'Độ khó', items: difficultyChoices, onPick: value => { update('difficulty', value as Difficulty); setChoice(null); } })} /><Select label="Môn học" value={subjectName} onPress={() => selectCatalog('Môn học', subjects, 'subjectId')} /><Select label="Chương" value={chapterName} onPress={() => selectCatalog('Chương', chapters, 'chapterId')} /><Select label="Chủ đề" value={topicName} onPress={() => selectCatalog('Chủ đề', topics, 'topicId')} /><Text style={styles.sectionTitle}>Nội dung câu hỏi</Text><Input label="Nội dung" value={form.content} onChangeText={value => update('content', value)} multiline /><Button title={form.imageUrl ? 'Đổi ảnh câu hỏi' : 'Chọn ảnh câu hỏi'} variant="secondary" loading={uploadingImage} disabled={uploadingImage} onPress={() => void pickImage('question')} />{form.imageUrl && <Text style={styles.fileStatus}>Đã tải ảnh minh họa.</Text>}<Text style={styles.helper}>JPEG, PNG, WEBP hoặc GIF, tối đa 5MB.</Text><Text style={styles.sectionTitle}>Phương án trả lời</Text>{form.options.map((option, index) => <View key={option.label} style={styles.optionEditor}><Input label={`Phương án ${option.label}`} value={option.content} onChangeText={value => updateOption(index, { content: value })} /><Button title={option.imageUrl ? `Đổi ảnh phương án ${option.label}` : `Chọn ảnh phương án ${option.label}`} variant="secondary" loading={uploadingImage} disabled={uploadingImage} onPress={() => void pickImage('option', index)} /><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: option.correct }} onPress={() => updateOption(index, { correct: !option.correct })}><Text style={[styles.correctToggle, option.correct && styles.correctSelected]}>{option.correct ? '✓ Đáp án đúng' : 'Chọn đáp án đúng'}</Text></Pressable></View>)}<Button title="Lưu bản nháp" loading={saving} disabled={saving || uploadingImage} onPress={() => void save()} /></Card><ChoiceModal choice={choice} onClose={() => setChoice(null)} /></AppScreen>;
}
function ChoiceModal({ choice, onClose }: { choice: { title: string; items: CatalogItem[] | string[]; onPick: (value: string) => void } | null; onClose: () => void }) { return <Modal visible={Boolean(choice)} transparent animationType="slide" onRequestClose={onClose}><Pressable style={styles.backdrop} onPress={onClose}><View style={styles.sheet} onStartShouldSetResponder={() => true}>{choice && <><Text style={styles.sheetTitle}>{choice.title}</Text>{choice.items.map(item => { const value = typeof item === 'string' ? item : item.id; const label = typeof item === 'string' ? item : item.name; return <Pressable key={value} accessibilityRole="button" onPress={() => choice.onPick(value)} style={styles.choice}><Text style={styles.choiceText}>{label}</Text></Pressable>; })}<Button title="Hủy" variant="secondary" onPress={onClose} /></>}</View></Pressable></Modal>; }
const styles = StyleSheet.create({ validation: { color: colors.danger, fontSize: typography.label, marginBottom: spacing.md }, sectionTitle: { color: colors.text, fontSize: typography.body, fontWeight: '700', marginTop: spacing.lg, marginBottom: spacing.md }, optionEditor: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border, gap: spacing.md, paddingTop: spacing.md }, helper: { color: colors.textSecondary, fontSize: typography.caption, marginTop: spacing.sm }, fileStatus: { color: colors.success, fontSize: typography.caption }, correctToggle: { borderColor: colors.border, borderRadius: radius.sm, borderWidth: 1, color: colors.textSecondary, padding: spacing.md }, correctSelected: { backgroundColor: '#E6F4EA', borderColor: colors.success, color: colors.success, fontWeight: '700' }, backdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.25)', justifyContent: 'flex-end' }, sheet: { backgroundColor: colors.surface, borderTopLeftRadius: radius.lg, borderTopRightRadius: radius.lg, gap: spacing.sm, maxHeight: '80%', padding: spacing.xl }, sheetTitle: { color: colors.text, fontSize: typography.heading, fontWeight: '700', marginBottom: spacing.sm }, choice: { borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: spacing.md }, choiceText: { color: colors.text, fontSize: typography.body } });
