/* eslint-disable react-hooks/set-state-in-effect -- preserve existing async screen-loading behavior. */
import { useCallback, useEffect, useState } from 'react';
import { Image, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { AppScreen, Button, Card, StatusBadge } from '@/src/components/ui';
import { AppHeader, EmptyState, ErrorState, LoadingIndicator } from '@/src/components/shared';
import { normalizeError } from '@/src/services/api/errors';
import { colors, spacing, typography } from '@/src/theme/tokens';
import { questionApi, type Question } from '../api/questionApi';

export function QuestionDetailScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const [question, setQuestion] = useState<Question | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const load = useCallback(async () => { if (!id) return; setLoading(true); setError(null); try { setQuestion(await questionApi.get(id)); } catch (cause) { setError(normalizeError(cause).message); } finally { setLoading(false); } }, [id]); useEffect(() => { void load(); }, [load]); async function submit() { if (!question) return; setBusy(true); setError(null); try { setQuestion(await questionApi.submit(question.id)); } catch (cause) { setError(normalizeError(cause).message); } finally { setBusy(false); } } if (loading) return <AppScreen><AppHeader title="Chi tiết câu hỏi" /><LoadingIndicator label="Đang tải câu hỏi" /></AppScreen>; if (error && !question) return <AppScreen><AppHeader title="Chi tiết câu hỏi" /><ErrorState title={error} onRetry={() => void load()} /></AppScreen>; if (!question) return <AppScreen><EmptyState title="Không tìm thấy câu hỏi" /> </AppScreen>; const editable = question.status === 'DRAFT' || question.status === 'NEED_REVISION'; const latestComment = [...question.reviewHistory].reverse().find(item => item.comment)?.comment; return <AppScreen scroll><AppHeader title="Chi tiết câu hỏi" /><Card><View style={styles.badges}><StatusBadge label={question.status} /><StatusBadge label={question.source} /><StatusBadge label={question.difficulty} /></View><Text style={styles.content}>{question.content}</Text>{question.imageUrl && <Image accessibilityLabel="Ảnh câu hỏi" source={{ uri: question.imageUrl }} style={styles.image} />}{question.options.map(option => <View key={option.id || option.label} style={styles.option}><Text style={[styles.optionText, option.correct && styles.correct]}>{option.label}. {option.content}{option.correct ? ' ✓' : ''}</Text>{option.imageUrl && <Image accessibilityLabel={`Ảnh phương án ${option.label}`} source={{ uri: option.imageUrl }} style={styles.optionImage} />}</View>)}<Text style={styles.explanation}>Loại câu hỏi: {question.type}</Text><Text style={styles.meta}>Cập nhật: {new Date(question.updatedAt).toLocaleString('vi-VN')}</Text>{latestComment && <View style={styles.comment}><Text style={styles.commentTitle}>Phản hồi từ Quản trị viên chuyên môn</Text><Text style={styles.meta}>{latestComment}</Text></View>}{error && <ErrorState title={error} />}{editable && <View style={styles.actions}><Button title="Chỉnh sửa câu hỏi" onPress={() => router.push({ pathname: '/question/edit/[id]', params: { id: question.id } })} /><Button title={question.status === 'NEED_REVISION' ? 'Gửi lại phê duyệt' : 'Gửi phê duyệt'} loading={busy} disabled={busy} onPress={() => void submit()} /></View>}</Card></AppScreen>; }
const styles = StyleSheet.create({ badges: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, content: { color: colors.text, fontSize: typography.body, lineHeight: 24, marginTop: spacing.lg }, image: { width: '100%', height: 180, borderRadius: 12, marginTop: spacing.md }, option: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, paddingVertical: spacing.md }, optionText: { color: colors.text, fontSize: typography.body }, correct: { color: colors.success, fontWeight: '700' }, optionImage: { width: '100%', height: 100, marginTop: spacing.sm }, explanation: { color: colors.textSecondary, fontSize: typography.caption, marginTop: spacing.lg }, meta: { color: colors.textSecondary, fontSize: typography.caption, marginTop: spacing.sm }, comment: { backgroundColor: colors.muted, borderRadius: 8, marginTop: spacing.lg, padding: spacing.md }, commentTitle: { color: colors.text, fontWeight: '700' }, actions: { gap: spacing.md, marginTop: spacing.lg } });
