import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import * as DocumentPicker from 'expo-document-picker';
import { Ionicons } from '@expo/vector-icons';
import { Alert, Image, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { AppScreen, Card } from '@/src/components/ui';
import { AppHeader, EmptyState, ErrorState, LoadingIndicator } from '@/src/components/shared';
import { useAuth } from '@/src/app/providers/AppProviders';
import { connectGatewaySocket, type GatewaySocketDisconnect } from '@/src/services/websocket/client';
import { normalizeError } from '@/src/services/api/errors';
import { useThemeColors } from '@/src/theme/useThemeColors';
import { radius, spacing, typography } from '@/src/theme/tokens';
import { ChatContact, ChatConversation, ChatMessage, mergeMessages, PickedImage, supportChatApi } from '../api/supportChatApi';

type Selection = { contact: ChatContact; conversation?: ChatConversation };
type BroadcastDraft = { group: string; content: string; image: PickedImage | null; count: number | null; loading: boolean };
type SupportEvent = { eventType?: string; conversationId?: string; message?: ChatMessage; senderId?: string; typing?: boolean };
const roleLabels = { SYSTEM_ADMIN: 'Quản trị viên hệ thống', SUBJECT_ADMIN: 'Quản trị viên chuyên môn', USER: 'Giảng viên' } as const;
const displayName = (contact?: ChatContact) => contact?.fullName?.trim() || contact?.displayName?.trim() || 'Không xác định';
const initials = (value: string) => value.trim().split(/\s+/).slice(-2).map(part => part[0]).join('').toUpperCase() || 'HA';
const messageTime = (value?: string) => value ? new Date(value).toLocaleString('vi-VN', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }) : '';

export function HumanChatScreen() {
  const { session } = useAuth(); const colors = useThemeColors(); const scrollRef = useRef<ScrollView>(null); const nearBottom = useRef(true); const socket = useRef<GatewaySocketDisconnect | null>(null); const typingTimer = useRef<ReturnType<typeof setTimeout> | null>(null); const typingSent = useRef(false);
  const currentRole = session?.role; const currentUserId = session?.userId;
  const [contacts, setContacts] = useState<ChatContact[]>([]); const [conversations, setConversations] = useState<ChatConversation[]>([]); const [selection, setSelection] = useState<Selection | null>(null); const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [query, setQuery] = useState(''); const [roleFilter, setRoleFilter] = useState(''); const [facultyFilter, setFacultyFilter] = useState(''); const [text, setText] = useState(''); const [image, setImage] = useState<PickedImage | null>(null); const [preview, setPreview] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [contactTyping, setContactTyping] = useState(false); const [broadcast, setBroadcast] = useState<BroadcastDraft | null>(null);

  const load = useCallback(async () => { setLoading(true); try { const [people, page] = await Promise.all([supportChatApi.contacts(query, roleFilter, facultyFilter), currentRole === 'SYSTEM_ADMIN' ? supportChatApi.admin() : currentRole === 'SUBJECT_ADMIN' ? supportChatApi.assigned() : supportChatApi.mine()]); setContacts(people); setConversations(page.content || []); setError(''); } catch (cause) { setError(normalizeError(cause).message); } finally { setLoading(false); } }, [currentRole, facultyFilter, query, roleFilter]);
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer); }, [load]);
  useEffect(() => { const connection = connectGatewaySocket({ onMessage: () => undefined, onSupport: value => { const event = value as SupportEvent; if (event.eventType === 'CHAT_TYPING' && event.conversationId === selection?.conversation?.id && event.senderId !== currentUserId) { setContactTyping(Boolean(event.typing)); return; } if (event.message && event.conversationId === selection?.conversation?.id) { setMessages(current => mergeMessages(current, event.message!)); if (nearBottom.current) requestAnimationFrame(() => scrollRef.current?.scrollToEnd({ animated: true })); } void load(); } }); socket.current = connection; return () => { if (typingTimer.current) clearTimeout(typingTimer.current); if (typingSent.current && selection?.conversation?.id) connection.sendTyping(selection.conversation.id, false); typingSent.current = false; socket.current = null; connection(); }; }, [currentUserId, load, selection?.conversation?.id]);

  const contactById = useMemo(() => new Map(contacts.map(contact => [contact.userId, contact])), [contacts]);
  const conversationContact = useCallback((conversation: ChatConversation) => { const otherId = conversation.createdByUserId === currentUserId ? conversation.assignedAdminId : conversation.createdByUserId; return otherId ? contactById.get(otherId) : undefined; }, [contactById, currentUserId]);
  const rows = useMemo<Selection[]>(() => { const conversationRows = conversations.map(conversation => ({ contact: conversationContact(conversation), conversation })).filter(row => row.contact) as Selection[]; const existing = new Set(conversationRows.map(row => row.contact.userId)); const newRows: Selection[] = contacts.filter(contact => !existing.has(contact.userId)).map(contact => ({ contact })); return [...conversationRows, ...newRows]; }, [contacts, conversationContact, conversations]);
  const faculties = useMemo(() => [...new Set(contacts.map(contact => contact.facultyId).filter(Boolean))] as string[], [contacts]);

  function stopTyping() { if (typingTimer.current) { clearTimeout(typingTimer.current); typingTimer.current = null; } if (typingSent.current && selection?.conversation?.id) socket.current?.sendTyping(selection.conversation.id, false); typingSent.current = false; }
  function changeText(value: string) { setText(value); if (!selection?.conversation?.id || !value.trim()) { stopTyping(); return; } if (!typingSent.current) { socket.current?.sendTyping(selection.conversation.id, true); typingSent.current = true; } if (typingTimer.current) clearTimeout(typingTimer.current); typingTimer.current = setTimeout(stopTyping, 2500); }
  async function open(row: Selection) { stopTyping(); setContactTyping(false); setSelection(row); setMessages([]); setText(''); setImage(null); setError(''); if (!row.conversation) return; try { const page = await supportChatApi.messages(row.conversation.id); setMessages((page.content || []).reverse().reduce((items, item) => mergeMessages(items, item), [] as ChatMessage[])); await supportChatApi.read(row.conversation.id); requestAnimationFrame(() => scrollRef.current?.scrollToEnd({ animated: false })); } catch (cause) { setError(normalizeError(cause).message); } }
  async function chooseImage() { const result = await DocumentPicker.getDocumentAsync({ type: ['image/png', 'image/jpeg', 'image/webp'], multiple: false, copyToCacheDirectory: true }); if (result.canceled) return; const asset = result.assets[0]; if ((asset.size || 0) > 10 * 1024 * 1024) { setError('Ảnh không được vượt quá 10 MB.'); return; } setImage({ uri: asset.uri, name: asset.name || 'chat-image', mimeType: asset.mimeType || 'image/jpeg' }); }
  async function pickBroadcastImage() { const result = await DocumentPicker.getDocumentAsync({ type: ['image/png', 'image/jpeg', 'image/webp'], multiple: false, copyToCacheDirectory: true }); if (result.canceled) return; const asset = result.assets[0]; if ((asset.size || 0) > 10 * 1024 * 1024) { setError('Ảnh không được vượt quá 10 MB.'); return; } setBroadcast(current => current ? { ...current, image: { uri: asset.uri, name: asset.name || 'broadcast-image', mimeType: asset.mimeType || 'image/jpeg' } } : current); }
  async function openBroadcast() { const group = currentRole === 'SUBJECT_ADMIN' ? 'FACULTY_USERS' : 'ALL'; setBroadcast({ group, content: '', image: null, count: null, loading: true }); try { const count = await supportChatApi.broadcastCount(group); setBroadcast(current => current?.group === group ? { ...current, count: Number(count) || 0, loading: false } : current); } catch (cause) { setBroadcast(null); setError(normalizeError(cause).message); } }
  async function changeBroadcastGroup(group: string) { setBroadcast(current => current ? { ...current, group, count: null, loading: true } : current); try { const count = await supportChatApi.broadcastCount(group); setBroadcast(current => current?.group === group ? { ...current, count: Number(count) || 0, loading: false } : current); } catch (cause) { setBroadcast(current => current ? { ...current, loading: false } : current); setError(normalizeError(cause).message); } }
  function confirmBroadcast() { if (!broadcast?.count) return; Alert.alert('Xác nhận gửi thông báo', `Tin nhắn sẽ được gửi tới ${broadcast.count} người.`, [{ text: 'Hủy', style: 'cancel' }, { text: 'Gửi', onPress: () => void performBroadcast() }]); }
  async function performBroadcast() { if (!broadcast || (!broadcast.content.trim() && !broadcast.image)) return; setBroadcast(current => current ? { ...current, loading: true } : current); try { const result = await supportChatApi.broadcast(broadcast.group, broadcast.content, broadcast.image); setBroadcast(null); Alert.alert('Đã gửi', `Thông báo đã được gửi tới ${result.deliveredCount} người.`); void load(); } catch (cause) { setBroadcast(current => current ? { ...current, loading: false } : current); setError(normalizeError(cause).message); } }
  async function send() { if (!selection || busy || (!text.trim() && !image)) return; const originalText = text; stopTyping(); setText(''); setBusy(true); setError(''); try { let conversation = selection.conversation; if (!conversation) { conversation = await supportChatApi.create(selection.contact.userId, `Trao đổi với ${displayName(selection.contact)}`); setSelection(current => current ? { ...current, conversation } : current); setConversations(current => [conversation!, ...current.filter(item => item.id !== conversation!.id)]); } const message = await supportChatApi.send(conversation.id, originalText, image); setMessages(current => mergeMessages(current, message)); setImage(null); nearBottom.current = true; requestAnimationFrame(() => scrollRef.current?.scrollToEnd({ animated: true })); void load(); } catch (cause) { setText(originalText); setError(normalizeError(cause).message); } finally { setBusy(false); } }

  if (selection) return <AppScreen><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
    <View style={[styles.chatHeader, { borderBottomColor: colors.border }]}><Pressable accessibilityLabel="Quay lại danh sách" onPress={() => setSelection(null)}><Ionicons name="chevron-back" size={26} color={colors.accent} /></Pressable><Avatar contact={selection.contact} /><View style={styles.grow}><Text style={[styles.name, { color: colors.text }]}>{displayName(selection.contact)}</Text><Text style={[styles.meta, { color: colors.textSecondary }]}>{roleLabels[selection.contact.role]}{selection.contact.facultyId ? ` · Khoa ${selection.contact.facultyId}` : ''}</Text></View></View>
    {error ? <ErrorState title={error} /> : null}
    <ScrollView ref={scrollRef} style={styles.messages} contentContainerStyle={styles.messageContent} onContentSizeChange={() => nearBottom.current && scrollRef.current?.scrollToEnd({ animated: false })} onScroll={event => { const { contentOffset, contentSize, layoutMeasurement } = event.nativeEvent; nearBottom.current = contentSize.height - (contentOffset.y + layoutMeasurement.height) < 90; }} scrollEventThrottle={80} keyboardShouldPersistTaps="handled">
      {!messages.length && <EmptyState title="Bắt đầu cuộc trò chuyện" description="Tin nhắn đầu tiên sẽ tạo cuộc trò chuyện và được lưu trên hệ thống." />}
      {messages.map(message => <View key={message.id} style={[styles.bubble, message.senderId === session?.userId ? styles.mine : styles.theirs, { backgroundColor: message.senderId === session?.userId ? colors.accentSoft : colors.surface, borderColor: colors.border }]}>{message.deleted ? <Text style={[styles.deleted, { color: colors.textSecondary }]}>Tin nhắn đã được thu hồi</Text> : <>{message.content ? <Text style={[styles.messageText, { color: colors.text }]}>{message.content}</Text> : null}{message.attachments?.map(attachment => <Pressable key={attachment.id} onPress={() => setPreview(attachment.url)}><Image source={{ uri: attachment.url }} style={styles.messageImage} accessibilityLabel={attachment.fileName} /></Pressable>)}</>}<Text style={[styles.time, { color: colors.textSecondary }]}>{messageTime(message.createdAt)}</Text></View>)}
    </ScrollView>
    {contactTyping && <View style={typingStyles.row}><Avatar contact={selection.contact} compact /><Text style={{ color: colors.textSecondary }}>{displayName(selection.contact)} đang nhập...</Text><View style={[typingStyles.dot, { backgroundColor: colors.accent }]} /><View style={[typingStyles.dot, { backgroundColor: colors.accent }]} /><View style={[typingStyles.dot, { backgroundColor: colors.accent }]} /></View>}
    {image && <View style={[styles.attachment, { backgroundColor: colors.muted }]}><Ionicons name="image-outline" size={20} color={colors.accent} /><Text numberOfLines={1} style={[styles.grow, { color: colors.text }]}>{image.name}</Text><Pressable accessibilityLabel="Bỏ ảnh" onPress={() => setImage(null)}><Ionicons name="close-circle" size={22} color={colors.danger} /></Pressable></View>}
    <View style={[styles.composer, { borderTopColor: colors.border, backgroundColor: colors.background }]}><Pressable accessibilityLabel="Chọn ảnh" style={styles.iconButton} onPress={() => void chooseImage()}><Ionicons name="image-outline" size={24} color={colors.accent} /></Pressable><TextInput value={text} onChangeText={changeText} onBlur={stopTyping} multiline maxLength={4000} placeholder="Nhập tin nhắn..." placeholderTextColor={colors.textSecondary} style={[styles.input, { color: colors.text, borderColor: colors.border, backgroundColor: colors.surface }]} /><Pressable accessibilityLabel="Gửi" disabled={busy || (!text.trim() && !image)} style={[styles.send, { backgroundColor: colors.accent }, (busy || (!text.trim() && !image)) && styles.disabled]} onPress={() => void send()}><Ionicons name="send" size={20} color={colors.white} /></Pressable></View>
    <Modal visible={Boolean(preview)} transparent animationType="fade" onRequestClose={() => setPreview(null)}><Pressable style={styles.fullPreview} onPress={() => setPreview(null)}>{preview && <Image source={{ uri: preview }} resizeMode="contain" style={styles.previewImage} />}</Pressable></Modal>
  </KeyboardAvoidingView></AppScreen>;

  return <AppScreen><AppHeader title="Tin nhắn" subtitle="Trao đổi nội bộ HAU Exam" />{(currentRole === 'SYSTEM_ADMIN' || currentRole === 'SUBJECT_ADMIN') && <Pressable style={[broadcastStyles.open, { borderColor: colors.accent }]} onPress={() => void openBroadcast()}><Ionicons name="megaphone-outline" size={18} color={colors.accent} /><Text style={{ color: colors.accent, fontWeight: '800' }}>Gửi thông báo hàng loạt</Text></Pressable>}<View style={[styles.searchRow, { borderColor: colors.border, backgroundColor: colors.surface }]}><Ionicons name="search" size={20} color={colors.textSecondary} /><TextInput value={query} onChangeText={setQuery} placeholder="Tìm tên, mã giảng viên hoặc email" placeholderTextColor={colors.textSecondary} style={[styles.search, { color: colors.text }]} /></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}><FilterChip label="Tất cả vai trò" active={!roleFilter} onPress={() => setRoleFilter('')} /><FilterChip label="Quản trị chuyên môn" active={roleFilter === 'SUBJECT_ADMIN'} onPress={() => setRoleFilter('SUBJECT_ADMIN')} /><FilterChip label="Giảng viên" active={roleFilter === 'USER'} onPress={() => setRoleFilter('USER')} /></ScrollView>
    {faculties.length > 0 && <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}><FilterChip label="Tất cả Khoa" active={!facultyFilter} onPress={() => setFacultyFilter('')} />{faculties.map(faculty => <FilterChip key={faculty} label={`Khoa ${faculty}`} active={facultyFilter === faculty} onPress={() => setFacultyFilter(faculty)} />)}</ScrollView>}
    {error ? <ErrorState title={error} onRetry={() => void load()} /> : loading ? <LoadingIndicator label="Đang tải tin nhắn" /> : <ScrollView contentContainerStyle={styles.list}>{rows.map(row => <Pressable key={row.contact.userId} onPress={() => void open(row)}><Card style={styles.contactCard}><Avatar contact={row.contact} /><View style={styles.grow}><View style={styles.nameRow}><Text numberOfLines={1} style={[styles.name, { color: colors.text }]}>{displayName(row.contact)}</Text>{row.conversation && <Text style={[styles.time, { color: colors.textSecondary }]}>{messageTime(row.conversation.lastMessageAt)}</Text>}</View><Text style={[styles.meta, { color: colors.textSecondary }]}>{roleLabels[row.contact.role]}{row.contact.facultyId ? ` · Khoa ${row.contact.facultyId}` : ''}</Text><Text numberOfLines={1} style={[row.conversation?.unreadCount ? styles.unreadPreview : styles.previewText, { color: colors.textSecondary }]}>{row.conversation?.lastMessage || 'Bắt đầu cuộc trò chuyện'}</Text></View>{Boolean(row.conversation?.unreadCount) && <View style={[styles.unread, { backgroundColor: colors.accent }]}><Text style={styles.unreadText}>{row.conversation!.unreadCount}</Text></View>}</Card></Pressable>)}{!rows.length && <EmptyState title="Không tìm thấy liên hệ" description="Thử đổi từ khóa hoặc bộ lọc." />}</ScrollView>}
    <Modal visible={Boolean(broadcast)} transparent animationType="slide" onRequestClose={() => !broadcast?.loading && setBroadcast(null)}>
      <View style={broadcastStyles.backdrop}>
        <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={[broadcastStyles.dialog, { backgroundColor: colors.surface }]}>
          <View style={broadcastStyles.titleRow}><View style={styles.grow}><Text style={[broadcastStyles.title, { color: colors.text }]}>Gửi thông báo hàng loạt</Text><Text style={[broadcastStyles.subtitle, { color: colors.textSecondary }]}>Hệ thống tự xác định người nhận theo quyền của bạn.</Text></View><Pressable accessibilityLabel="Đóng" disabled={broadcast?.loading} onPress={() => setBroadcast(null)}><Ionicons name="close" size={25} color={colors.textSecondary} /></Pressable></View>
          {currentRole === 'SYSTEM_ADMIN' ? <View style={broadcastStyles.groups}>{[['ALL', 'Tất cả người dùng'], ['SUBJECT_ADMIN', 'Quản trị viên chuyên môn'], ['USER', 'Giảng viên']].map(([group, label]) => <Pressable key={group} onPress={() => void changeBroadcastGroup(group)} style={[broadcastStyles.group, { borderColor: broadcast?.group === group ? colors.accent : colors.border, backgroundColor: broadcast?.group === group ? colors.accentSoft : colors.background }]}><Text style={{ color: broadcast?.group === group ? colors.accent : colors.text, fontWeight: '700' }}>{label}</Text></Pressable>)}</View> : <View style={[broadcastStyles.scope, { backgroundColor: colors.accentSoft }]}><Ionicons name="people-outline" size={19} color={colors.accent} /><Text style={{ color: colors.accent, flex: 1 }}>Tất cả giảng viên đang hoạt động trong Khoa của bạn</Text></View>}
          <TextInput multiline maxLength={4000} value={broadcast?.content || ''} onChangeText={content => setBroadcast(current => current ? { ...current, content } : current)} placeholder="Nhập nội dung thông báo..." placeholderTextColor={colors.textSecondary} style={[broadcastStyles.input, { color: colors.text, borderColor: colors.border, backgroundColor: colors.background }]} />
          {broadcast?.image ? <View style={[styles.attachment, { backgroundColor: colors.muted }]}><Ionicons name="image-outline" size={20} color={colors.accent} /><Text numberOfLines={1} style={[styles.grow, { color: colors.text }]}>{broadcast.image.name}</Text><Pressable accessibilityLabel="Bỏ ảnh" onPress={() => setBroadcast(current => current ? { ...current, image: null } : current)}><Ionicons name="close-circle" size={22} color={colors.danger} /></Pressable></View> : <Pressable style={[broadcastStyles.imageButton, { borderColor: colors.border }]} onPress={() => void pickBroadcastImage()}><Ionicons name="image-outline" size={20} color={colors.accent} /><Text style={{ color: colors.accent, fontWeight: '700' }}>Đính kèm ảnh</Text></Pressable>}
          <Text style={[broadcastStyles.count, { color: colors.text }]}>{broadcast?.loading || broadcast?.count == null ? 'Đang xác định số người nhận...' : `Tin nhắn sẽ được gửi tới ${broadcast.count} người.`}</Text>
          <View style={broadcastStyles.actions}><Pressable disabled={broadcast?.loading} style={[broadcastStyles.action, { borderColor: colors.border }]} onPress={() => setBroadcast(null)}><Text style={{ color: colors.text, fontWeight: '700' }}>Hủy</Text></Pressable><Pressable disabled={broadcast?.loading || !broadcast?.count || (!broadcast?.content.trim() && !broadcast?.image)} style={[broadcastStyles.action, { backgroundColor: colors.accent }, (broadcast?.loading || !broadcast?.count || (!broadcast?.content.trim() && !broadcast?.image)) && styles.disabled]} onPress={confirmBroadcast}><Text style={{ color: colors.white, fontWeight: '800' }}>Gửi</Text></Pressable></View>
        </KeyboardAvoidingView>
      </View>
    </Modal>
  </AppScreen>;
}

function Avatar({ contact, compact = false }: { contact: ChatContact; compact?: boolean }) { const colors = useThemeColors(); const avatarStyle = [styles.avatar, compact && typingStyles.avatar]; return contact.avatarUrl ? <Image source={{ uri: contact.avatarUrl }} style={avatarStyle} /> : <View style={[...avatarStyle, styles.avatarFallback, { backgroundColor: colors.accentSoft }]}><Text style={[styles.avatarText, compact && typingStyles.avatarText, { color: colors.accent }]}>{initials(displayName(contact))}</Text></View>; }
function FilterChip({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { const colors = useThemeColors(); return <Pressable onPress={onPress} style={[styles.chip, { borderColor: active ? colors.accent : colors.border, backgroundColor: active ? colors.accentSoft : colors.surface }]}><Text style={{ color: active ? colors.accent : colors.textSecondary, fontWeight: '700', fontSize: typography.caption }}>{label}</Text></Pressable>; }
const broadcastStyles = StyleSheet.create({ open: { alignItems: 'center', alignSelf: 'flex-start', borderRadius: radius.md, borderWidth: 1, flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, backdrop: { backgroundColor: 'rgba(9, 25, 44, 0.55)', flex: 1, justifyContent: 'flex-end' }, dialog: { borderTopLeftRadius: 22, borderTopRightRadius: 22, gap: spacing.md, maxHeight: '88%', padding: spacing.xl, paddingBottom: Platform.OS === 'ios' ? 36 : spacing.xl }, titleRow: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md }, title: { fontSize: typography.heading, fontWeight: '800' }, subtitle: { fontSize: typography.caption, lineHeight: 18, marginTop: spacing.xs }, groups: { gap: spacing.sm }, group: { borderRadius: radius.md, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: 11 }, scope: { alignItems: 'center', borderRadius: radius.md, flexDirection: 'row', gap: spacing.sm, padding: spacing.md }, input: { borderRadius: radius.md, borderWidth: StyleSheet.hairlineWidth, fontSize: typography.body, minHeight: 112, padding: spacing.md, textAlignVertical: 'top' }, imageButton: { alignItems: 'center', borderRadius: radius.md, borderStyle: 'dashed', borderWidth: 1, flexDirection: 'row', gap: spacing.sm, justifyContent: 'center', padding: spacing.md }, count: { fontSize: typography.label, fontWeight: '700' }, actions: { flexDirection: 'row', gap: spacing.sm }, action: { alignItems: 'center', borderRadius: radius.md, borderWidth: StyleSheet.hairlineWidth, flex: 1, justifyContent: 'center', minHeight: 46, paddingHorizontal: spacing.md } });
const typingStyles = StyleSheet.create({ row: { alignItems: 'center', alignSelf: 'flex-end', flexDirection: 'row', gap: 5, marginBottom: spacing.sm, maxWidth: '90%' }, dot: { borderRadius: 3, height: 5, width: 5 }, avatar: { borderRadius: 11, height: 22, width: 22 }, avatarText: { fontSize: 8 } });
const styles = StyleSheet.create({ flex: { flex: 1 }, grow: { flex: 1 }, searchRow: { alignItems: 'center', borderRadius: radius.md, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: spacing.sm, minHeight: 46, paddingHorizontal: spacing.md }, search: { flex: 1, fontSize: typography.label }, filters: { gap: spacing.sm, paddingVertical: spacing.sm }, chip: { borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, list: { gap: spacing.sm, paddingBottom: 110 }, contactCard: { alignItems: 'center', flexDirection: 'row', gap: spacing.md }, avatar: { borderRadius: 23, height: 46, width: 46 }, avatarFallback: { alignItems: 'center', justifyContent: 'center' }, avatarText: { fontSize: typography.label, fontWeight: '800' }, nameRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm }, name: { flex: 1, fontSize: typography.label, fontWeight: '800' }, meta: { fontSize: typography.caption, marginTop: 2 }, previewText: { fontSize: typography.caption, marginTop: spacing.xs }, unreadPreview: { fontSize: typography.caption, fontWeight: '800', marginTop: spacing.xs }, unread: { alignItems: 'center', borderRadius: 11, justifyContent: 'center', minHeight: 22, minWidth: 22, paddingHorizontal: 5 }, unreadText: { color: '#fff', fontSize: 11, fontWeight: '800' }, chatHeader: { alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: spacing.md, paddingBottom: spacing.md }, messages: { flex: 1 }, messageContent: { gap: spacing.sm, paddingVertical: spacing.md }, bubble: { borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, maxWidth: '84%', padding: spacing.md }, mine: { alignSelf: 'flex-end', borderBottomRightRadius: 4 }, theirs: { alignSelf: 'flex-start', borderBottomLeftRadius: 4 }, messageText: { fontSize: typography.body, lineHeight: 22 }, deleted: { fontSize: typography.label, fontStyle: 'italic' }, time: { fontSize: 10, marginTop: spacing.xs }, messageImage: { borderRadius: radius.md, height: 180, marginBottom: spacing.xs, width: 220 }, attachment: { alignItems: 'center', borderRadius: radius.md, flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.sm, padding: spacing.sm }, composer: { alignItems: 'flex-end', borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: spacing.sm, paddingTop: spacing.sm }, iconButton: { alignItems: 'center', height: 44, justifyContent: 'center', width: 40 }, input: { borderRadius: 20, borderWidth: StyleSheet.hairlineWidth, flex: 1, fontSize: typography.body, maxHeight: 112, minHeight: 44, paddingHorizontal: spacing.md, paddingVertical: 10 }, send: { alignItems: 'center', borderRadius: 22, height: 44, justifyContent: 'center', width: 44 }, disabled: { opacity: 0.45 }, fullPreview: { backgroundColor: 'rgba(0,0,0,0.92)', flex: 1, justifyContent: 'center', padding: spacing.md }, previewImage: { height: '100%', width: '100%' } });
