/* eslint-disable react-hooks/set-state-in-effect -- preserve existing async screen-loading behavior. */
import { useCallback, useEffect, useState } from 'react';
import { Image, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { AppScreen, Button, Card, ConfirmModal, Input, StatusBadge } from '@/src/components/ui';
import { AppHeader, EmptyState, ErrorState, LoadingIndicator } from '@/src/components/shared';
import { normalizeError } from '@/src/services/api/errors';
import { colors, radius, spacing, typography } from '@/src/theme/tokens';
import { questionApi, type Question } from '@/src/features/questions/api/questionApi';

type ReviewAction = 'revision' | 'reject';
function safeError(error: unknown) { const normalized = normalizeError(error); return normalized.kind === 'FORBIDDEN' ? 'Bạn không có quyền xử lý câu hỏi ngoài phạm vi Khoa.' : normalized.message; }

export function ReviewDetailScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const [question, setQuestion] = useState<Question | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [confirmApprove, setConfirmApprove] = useState(false); const [action, setAction] = useState<ReviewAction | null>(null); const [reason, setReason] = useState(''); const load = useCallback(async () => { if (!id) return; setLoading(true); setError(null); try { setQuestion(await questionApi.get(id)); } catch (cause) { setError(safeError(cause)); } finally { setLoading(false); } }, [id]); useEffect(() => { void load(); }, [load]); async function approve() { if (!question) return; setBusy(true); setError(null); try { await questionApi.approve(question.id); router.back(); } catch (cause) { setError(safeError(cause)); } finally { setBusy(false); setConfirmApprove(false); } } async function submitReason() { if (!question || !action || !reason.trim()) return; setBusy(true); setError(null); try { if (action === 'reject') await questionApi.reject(question.id, reason.trim()); else await questionApi.requestRevision(question.id, reason.trim()); router.back(); } catch (cause) { setError(safeError(cause)); } finally { setBusy(false); setAction(null); setReason(''); } }
  if (loading) return <AppScreen><AppHeader title="Chi tiết phê duyệt" /><LoadingIndicator label="Đang tải câu hỏi" /></AppScreen>; if (error && !question) return <AppScreen><AppHeader title="Chi tiết phê duyệt" /><ErrorState title={error} onRetry={() => void load()} /></AppScreen>; if (!question) return <AppScreen><EmptyState title="Không tìm thấy câu hỏi" /></AppScreen>;
  return <AppScreen scroll><AppHeader title="Chi tiết phê duyệt" subtitle="Phạm vi Khoa được kiểm tra bởi backend" />{error && <ErrorState title={error} />}<Card><View style={styles.badges}><StatusBadge label={question.status} /><StatusBadge label={question.source} /><StatusBadge label={question.difficulty} /></View><Text style={styles.content}>{question.content}</Text>{question.imageUrl && <Image accessibilityLabel="Ảnh câu hỏi" source={{ uri: question.imageUrl }} style={styles.image} />}{question.options.map(option => <View key={option.id || option.label} style={styles.option}><Text style={[styles.optionText, option.correct && styles.correct]}>{option.label}. {option.content}{option.correct ? ' ✓' : ''}</Text>{option.imageUrl && <Image accessibilityLabel={`Ảnh phương án ${option.label}`} source={{ uri: option.imageUrl }} style={styles.optionImage} />}</View>)}<Text style={styles.meta}>Người tạo: {question.createdBy}</Text><Text style={styles.meta}>Môn học: {question.subjectId}</Text><Text style={styles.meta}>Chương: {question.chapterId}</Text><Text style={styles.meta}>Chủ đề: {question.topicId || '—'}</Text><Text style={styles.meta}>Loại câu hỏi: {question.type}</Text><Text style={styles.sectionTitle}>Lịch sử phê duyệt</Text>{question.reviewHistory.length ? question.reviewHistory.map(item => <View key={item.id} style={styles.history}><Text style={styles.historyAction}>{item.action}</Text><Text style={styles.meta}>{item.comment || '—'} • {new Date(item.timestamp).toLocaleString('vi-VN')}</Text></View>) : <Text style={styles.meta}>Chưa có lịch sử phê duyệt</Text>}<View style={styles.actions}><Button title="Phê duyệt" loading={busy && confirmApprove} disabled={busy} onPress={() => setConfirmApprove(true)} /><Button title="Yêu cầu chỉnh sửa" variant="secondary" disabled={busy} onPress={() => { setAction('revision'); setReason(''); }} /><Button title="Từ chối" variant="destructive" disabled={busy} onPress={() => { setAction('reject'); setReason(''); }} /></View></Card><ConfirmModal visible={confirmApprove} title="Phê duyệt câu hỏi?" description="Câu hỏi sẽ được chuyển vào ngân hàng câu hỏi theo workflow hiện tại." onCancel={() => setConfirmApprove(false)} onConfirm={() => void approve()} /><ReasonModal action={action} reason={reason} busy={busy} onChange={setReason} onCancel={() => setAction(null)} onConfirm={() => void submitReason()} /></AppScreen>;
}
function ReasonModal({ action, reason, busy, onChange, onCancel, onConfirm }: { action: ReviewAction | null; reason: string; busy: boolean; onChange: (value: string) => void; onCancel: () => void; onConfirm: () => void }) { const title = action === 'reject' ? 'Từ chối câu hỏi' : 'Yêu cầu chỉnh sửa'; return <Modal visible={Boolean(action)} transparent animationType="slide" onRequestClose={onCancel}><Pressable style={styles.backdrop} onPress={onCancel}><View style={styles.sheet} onStartShouldSetResponder={() => true}><Text style={styles.sheetTitle}>{title}</Text><Text style={styles.meta}>Vui lòng nhập lý do để người tạo cập nhật nội dung.</Text><Input label="Lý do / nhận xét" value={reason} onChangeText={onChange} multiline /><View style={styles.modalActions}><Button title="Hủy" variant="secondary" onPress={onCancel} /><Button title="Xác nhận" loading={busy} disabled={!reason.trim() || busy} onPress={onConfirm} /></View></View></Pressable></Modal>; }
const styles = StyleSheet.create({ badges: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, content: { color: colors.text, fontSize: typography.body, lineHeight: 24, marginTop: spacing.lg }, image: { borderRadius: radius.md, height: 180, marginTop: spacing.md, width: '100%' }, option: { borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: spacing.md }, optionText: { color: colors.text, fontSize: typography.body }, correct: { color: colors.success, fontWeight: '700' }, optionImage: { height: 100, marginTop: spacing.sm, width: '100%' }, meta: { color: colors.textSecondary, fontSize: typography.caption, marginTop: spacing.sm }, sectionTitle: { color: colors.text, fontSize: typography.body, fontWeight: '700', marginTop: spacing.lg }, history: { backgroundColor: colors.muted, borderRadius: radius.sm, marginTop: spacing.sm, padding: spacing.md }, historyAction: { color: colors.text, fontWeight: '700' }, actions: { gap: spacing.md, marginTop: spacing.xl }, backdrop: { backgroundColor: 'rgba(0,0,0,0.25)', flex: 1, justifyContent: 'flex-end' }, sheet: { backgroundColor: colors.surface, borderTopLeftRadius: radius.lg, borderTopRightRadius: radius.lg, gap: spacing.md, padding: spacing.xl }, sheetTitle: { color: colors.text, fontSize: typography.heading, fontWeight: '700' }, modalActions: { flexDirection: 'row', gap: spacing.md } });
