/* eslint-disable react-hooks/set-state-in-effect -- preserve existing async review-loading behavior. */
import { useCallback, useEffect, useState } from 'react';
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { AppScreen, Card, StatusBadge } from '@/src/components/ui';
import { AppHeader, EmptyState, ErrorState, LoadingIndicator } from '@/src/components/shared';
import { normalizeError } from '@/src/services/api/errors';
import { colors, spacing, typography } from '@/src/theme/tokens';
import { questionApi, type Question } from '@/src/features/questions/api/questionApi';

function reviewError(error: unknown) { const normalized = normalizeError(error); return normalized.kind === 'FORBIDDEN' ? 'Bạn không có quyền xem câu hỏi ngoài phạm vi Khoa của mình.' : normalized.message; }
function submittedAt(question: Question) { return question.reviewHistory.find(history => history.action === 'SUBMITTED')?.timestamp || question.updatedAt; }

export function ReviewScreen() { const router = useRouter(); const [items, setItems] = useState<Question[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null); const load = useCallback(async (isRefresh = false) => { if (isRefresh) setRefreshing(true); else setLoading(true); setError(null); try { setItems((await questionApi.search({ status: 'PENDING_REVIEW', page: 0, size: 20 })).items); } catch (cause) { setError(reviewError(cause)); } finally { setLoading(false); setRefreshing(false); } }, []); useEffect(() => { void load(); }, [load]); if (loading) return <RoleReviewScreen><LoadingIndicator label="Đang tải hàng đợi phê duyệt" /></RoleReviewScreen>; return <RoleReviewScreen><View style={styles.scopeNote}><Text style={styles.scopeText}>Chỉ hiển thị câu hỏi trong phạm vi Khoa của bạn.</Text></View>{error ? <ErrorState title={error} onRetry={() => void load()} /> : <FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={items.length ? styles.list : styles.emptyList} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.accent} />} renderItem={({ item }) => <Pressable accessibilityRole="button" onPress={() => router.push({ pathname: '/review/[id]', params: { id: item.id } })}><Card><Text numberOfLines={3} style={styles.preview}>{item.content}</Text><Text style={styles.meta}>Người tạo: {item.createdBy}</Text><Text style={styles.meta}>Môn: {item.subjectId} • Chủ đề: {item.topicId || '—'}</Text><View style={styles.badges}><StatusBadge label={item.difficulty} /><StatusBadge label={item.source} /><Text style={styles.meta}>Gửi ngày {new Date(submittedAt(item)).toLocaleDateString('vi-VN')}</Text></View></Card></Pressable>} ListEmptyComponent={<EmptyState title="Hàng đợi đang trống" description="Hiện không có câu hỏi chờ phê duyệt trong phạm vi Khoa." />} />}</RoleReviewScreen>; }
function RoleReviewScreen({ children }: { children: React.ReactNode }) { return <AppScreen><AppHeader title="Duyệt câu hỏi" subtitle="Quản trị viên chuyên môn" />{children}</AppScreen>; }
const styles = StyleSheet.create({ scopeNote: { backgroundColor: colors.muted, borderRadius: 8, marginBottom: spacing.md, padding: spacing.md }, scopeText: { color: colors.textSecondary, fontSize: typography.caption }, list: { gap: spacing.md, paddingBottom: spacing.xl }, emptyList: { flexGrow: 1 }, preview: { color: colors.text, fontSize: typography.body, fontWeight: '600' }, meta: { color: colors.textSecondary, fontSize: typography.caption, marginTop: spacing.sm }, badges: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.md } });
